### ISSUE TITLE
[OpenType features not in TTFs] I cannot access ligatures in Word

### ISSUE THREAD

**Issue by thiagovscoelho** [indestructible-type/Bodoni#7] opened 2019-01-31 18:53 UTC
I know the ligatures (ff, ffi, fi) exist, because they work on the website. But even turning on “all” ligatures in Word, they do not appear. I don’t know why. This has also been tested in the newer versions of Windows and Office, but I am on the W7/2010 PC right now.

![winword_2019-01-31_16-51-38](https://user-images.githubusercontent.com/47187428/52077592-7faf2a00-2578-11e9-8f15-9cf4534f54ea.png)

**Comment by thiagovscoelho** [comment] 2019-01-31 20:02
I just downloaded it again from indestructibletype.com and reinstalled it, and the issue persisted. However, I noticed that despite the fact I had just downloaded it, the readme file still says it is version 1.0.  So I got it from GitHub and made sure to install from the “Finished” folder. Didn’t work either. Then I tried the “Finished” OTFs instead for good measure. No dice.

All sorts of fonts have working ligatures, such as, in the same style, Old Standard TT and Playfair Display. The free (OFL) one I know with the most working ligatures is Cormorant.

**Comment by Alice196498** [comment] 2019-01-31 20:15
Looking at it, it ſeems that the Readme ſtill ſays 1.0, and the Roman founts are all verſion 1.0 as well. Here on Github, the Italick founts all ſay 1.1, but the internal liſting (at leaſt in FontLab) is ſtill 1.0.

**Comment by thiagovscoelho** [comment] 2019-01-31 20:33
I just opened Word again and it worked! So I tried the “Finished” TTFs again for good measure and it didn’t again. So in all, it appears that you somehow failed to get the OpenType features into the TrueType files.

**Comment by thiagovscoelho** [comment] 2019-01-31 20:34
This version control weirdness could probably be its own issue too, but not sure.

**Comment by EwonRael** [comment] 2019-01-31 20:45
Thank you guys for your help troubleshooting this. 

I know there are some inconsistencies with the version numbers. This is mostly because I wanted to get the fixed version of the ligatures out the door as soon as humanly possible so the least number of people would have to see my embarrassing, broken ligatures. I didn't bother with the version numbers.

The insight that it's only with the .ttf files is extremely helpful! I am now able to reproduce the problem, and more importantly know how to fix it. 

The .ttf file format uses a different kind of Bezier spline than the .otf file, and as a result I have to make several changes to the font when going from .otf to .ttf in order to maintain a good quality. However, at some point during this process the ligatures are lost! 

I will fix this ASAP. Thank you both!

**Comment by Alice196498** [comment] 2019-01-31 20:47
Oh ! that’s very intereſting. It might be a good idea to document the changes, as well as what you do to fix it in caſe anyone elſe has this iſſue in the future.

**Comment by EwonRael** [comment] 2019-02-01 06:36
Okay!

I got version 1.2 up and running which should address metadata issues. Ligatures should be working and the version number inconsistency should be fixed.

Fingers crossed that this is what we need. Thank you both for your help.

**Closed by EwonRael** 2019-02-01 06:36 UTC

**Comment by thiagovscoelho** [comment] 2019-02-01 12:19
q
