### ISSUE TITLE
TTFs have no ligatures [on Word 2010]; OTFs [we]re invisible

### ISSUE THREAD

**Issue by thiagovscoelho** [indestructible-type/Bodoni#9] opened 2019-02-01 12:31 UTC
![stylelinks](https://user-images.githubusercontent.com/47187428/52122942-cbf77a00-260b-11e9-9c70-fc404f630efc.png)
The good news is now we have style links. The bad news is ligatures still don’t work – and I did check that they are on. So I tried the OTFs:
![winword_2019-02-01_10-30-21](https://user-images.githubusercontent.com/47187428/52123165-65bf2700-260c-11e9-87aa-c09fb437926f.png)
And now the fonts are fully invisible and it is impossible to type any text.

**Comment by thiagovscoelho** [comment] 2019-02-01 12:34
I know this is similar to the old ones but those are closed and I don’t think I can reopen them.

**Comment by EwonRael** [comment] 2019-02-01 17:52
No, it's my fault for being so excited to close the issue I didn't wait to see if it actually fixed the problem.

I have no idea what's causing this. I could recreate the previous issues by opening the fonts up in libre office writer, but that's now working fine.

It feels like a real one step forward two steps backwards situation.

I'm going to try some things and see if that works and I'll get back to you.

**Comment by thiagovscoelho** [comment] 2019-02-01 19:08
I tried it, same thing as before (TTFs without ligatures, OTFs invisible)

**Comment by thiagovscoelho** [comment] 2019-02-01 19:10
![explorer_2019-02-01_17-10-16](https://user-images.githubusercontent.com/47187428/52144047-447a2d00-2644-11e9-8a2c-648f4e2500a4.png)
Info probably not valuable, but Windows can’t see the glyphs in the OTFs even to make file thumbnails; the TTFs did have nice little thumbnails iirc

**Comment by thiagovscoelho** [comment] 2019-02-01 20:37
![winword_2019-02-01_18-37-03](https://user-images.githubusercontent.com/47187428/52148302-624d8f00-2650-11e9-851e-d0646712c358.png)
No :/

**Comment by thiagovscoelho** [comment] 2019-02-01 20:39
Bet I look stupid with all the dumb SoftMaker styles of Bodoni lol, anyway your font is the blank spaces there

**Comment by EwonRael** [comment] 2019-02-01 20:51
Okay.

I honestly don't know why this is happening or how to troubleshoot it at this point.

I will think about this a bit and get back to you but right now I'm honestly lost.

**Comment by EwonRael** [comment] 2019-02-01 21:01
I have little hope that this will work, but it's worth a shot.

[test.zip](https://github.com/indestructible-type/Bodoni/files/2823330/test.zip)

**Comment by Alice196498** [comment] 2019-02-02 00:18
One thing that might be affecting it is Windows itſelf. Windows has, in my experience, occaſionally run into problems when inſtalling new founts over old ones—to fix it, it’s generally beſt to run ſomething like the following in the command line (it might alſo help to do this in ſafe mode) : `del /f /s /q /a "\\<Name of PC>\c$\Windows\Fonts\<Name of typeface>_*"`
 The reaſon for running this is that Windows will at times make copies of the fount files, and they end up confuſing everything as to what ought to be uſed and what not to uſe. So it’s ſometimes good to make ſure they’re properly deleted. It’s alſo the beſt practice to reſtart the ſyſtem after inſtalling a new fount, eſpecially if it’s replacing an old one.

**Comment by EwonRael** [comment] 2019-02-02 01:04
Thanks! Let's hope this is the underlying problem.

**Comment by EwonRael** [comment] 2019-02-02 19:16
Okay.

The weird crossbar thing has mainly to do with the "test" version of the font files I gave you. If you were to download and install the fonts off of the website _that_ at the very least wouldn’t be a problem.

I have to throw in the towel with this one for now. I honestly don't know what is going on or how to help fix it. Part of me suspects it has less to do with the fonts and more to do with your system for some reason.

I want to be helpful, but I just don't know of anything I can do.

**Comment by thiagovscoelho** [comment] 2019-02-02 20:46
Well, this system has worked fine with all sorts of fonts. The latest test also shows the same issues on LibreOffice Writer, though LibreOffice can display some of the capitals (albeit with the same broken intersections).

For what it’s worth, I tried the latest release version from indestructibletype.com on LibreOffice and I could reproduce just fine the fact that both the OTF and TTF version seem to work perfectly on it. But on Word it’s still the same behavior: TTFs have no ligatures and OTFs are invisible.

I’m not sure what Word does differently, but Word has always worked better with TTFs for historical reasons: they look better on screen, and Word can only embed fonts in PDFs if they are TTFs, which is why I tried TTFs first since I first started testing. I haven’t researched more on this though.

**Comment by thiagovscoelho** [comment] 2019-02-02 20:50
I will try with the W10 laptop, which has a newer version of Office, when I get home. But I can’t imagine anything about this system specifically that could cause the fonts to behave worse.

**Comment by Alice196498** [comment] 2019-02-03 01:11
It’s not ſpecifick to Windows 7. I uſe Windows 10. While there are indeed problems with the files, it’s true that the glyphs in the OTF files appear in certain programs—I tried with InDeſign juſt now as a teſt.

**Comment by EwonRael** [comment] 2019-02-03 02:45
![capture](https://user-images.githubusercontent.com/16858124/52171777-bc655780-2717-11e9-850d-8f004fe7bba8.PNG)
![capture](https://user-images.githubusercontent.com/16858124/52171821-4ad9d900-2718-11e9-926a-8445c55d9230.PNG)


This is what Bodoni* looks like on the windows 10 PC I am testing it on. This is the 1.2 version that I downloaded from the indestructible type* website. Bodoni* is functional on every program I have tested it on. Pictured is Notepad and Word.

I can't reproduce this issue. 

I believe that you guys are experiencing it, but I don't know how to troubleshoot it because I can't reproduce it, and I also have no idea why it's happening. 

I don't know why this is happening. I am out of ideas. I'm pulling my hair out here. There doesn't appear to be anything wrong with the font files. I have tested the font files on windows, mac, and linux. The font files work fine on every computer and every program I have tested. 

I have to assume that windows is having a hard time dealing with upgrading the font files. All of you upgraded the font before experiencing these issues, yes? I have no evidence that the font files are corrupt or weird in any way. 

I have to take a break from troubleshooting this because it is stressing my out greatly.

**Comment by Alice196498** [comment] 2019-02-03 02:51
I ſuſpected ſomething like this would happen, which is why I made ſure to do ſome teſts without ever having inſtalled the founts. I ſhall do more teſting to ſee if I can diſcern anything. I ſhall alſo note that I downloaded the files I teſted with directly from the GitHub here. I amn’t ſure what exactly the iſſue is, but I will ſee if I can figure anything out. Try to reſt for now—it’s important that you try not to ſtreſs yourſelf.

**Comment by Alice196498** [comment] 2019-02-03 03:18
I’ve done a little more teſting, and the OTF files ſeem to be fully viſible on Linux ; thus, it ſeems to have ſomething to do with Windows. I’ve inſtalled the files on a Windows 10 ſyſtem that never had any previous verſions inſtalled on a freſh download of the typeface, which ſhould perhaps prove that it’s not an iſſue with updating or uninſtalling. The inſtall window doeſn’t diſplay the OTF files, and in Notepad, Windows is ſubſtituting a different typeface.

**Comment by Alice196498** [comment] 2019-02-03 04:04
What all exactly was changed between the older verſion and the neweſt verſion of the OTF ?

**Comment by EwonRael** [comment] 2019-02-03 04:38
I've had a breakthrough! Not a solution, unfortunately. 

The thing that changed between the versions was the metadata and the computer that I am using to generate the font files.

**I have been able to recreate the issue**, using of all things Google Drive. When I preview the older version of the otf font in Google Drive it generates a preview and print out of the font. However, when I try and do the same with the newer version of the font it tells me it cannot make a preview.

If I download the older version of the otf font onto a borrowed windows computer and re upload it to Google Drive it can still make a preview of the font. However, if I download the older version of the otf font onto my laptop and re upload it to the Google Drive it cannot generate a preview of the font. 

I'm literally just downloading it and re uploading it and it breaks it for some reason! I'm not even opening it in any programs. For some godforsaken reason the font breaks if it even touches my laptop.

Unfortunately, I am away on travel and do not have access to my desktop computer. I have no idea why this would be the case, but I think the only real solution is to wait until I am back home and can generate the font files on my desktop computer.

Until then just use the ttf files. The ligatures are broken when in word for some reason, but the ligatures work in notepad.

**Comment by Alice196498** [comment] 2019-02-03 04:59
It ſeems that the UPM ſize, as well as the family name is deleted ; moreover, I believe that ſome other metadata is being changed or deleted that I’m not ſeeing. The UPM ſize is the biggeſt change, I think, becauſe I can change it and the glyphs will render upon rebuilding the fount, but the kerning and various other features break, perhaps due to the other metadata, or poſſibly the change of UPM ſize and reſcaling thereby. As for the ligatures, I can’t really ſee what’s cauſing it, but I ſurmiſe that it could be due to the names of the ligatures being non-ſtandard ; for example, `sub f i by uniFB01;` and `sub f j by fj.lig;` theſe would uſually be named f_i and f_j reſpectively. The Unicode name ought to work, I reckon, but I don’t uſually ſee it uſed that way with theſe ligatures.

**Comment by EwonRael** [comment] 2019-02-03 12:54
@Alice196498 I appreciate the instinct that says there must be something about the metadata is causing this problem. However. I don't think that's the case. I think for whatever reason, just being on my laptop computer is enough to make the font files not work with Windows. Attached is a copy of a font file from the working 1.0 release of Bodoni*. I have simply downloaded it to my laptop computer and uploaded it here. I have done nothing else with it. I haven't opened it with any programs, or changed the name or anything.

I believe that this will have the same issues that you are experiencing. 

[Bodoni-16-Book.otf.zip](https://github.com/indestructible-type/Bodoni/files/2825513/Bodoni-16-Book.otf.zip)

**Comment by Alice196498** [comment] 2019-02-03 13:11
I’ve teſted the file you juſt uploaded, and it does not diſplay any of the iſſues found with the new files ; moreover, the metadata that I ſee does look fine in this file.

![image](https://user-images.githubusercontent.com/30258857/52177175-923b9480-2800-11e9-90cb-dbd554560d96.png)

**Comment by thiagovscoelho** [comment] 2019-02-03 15:45
I didn’t run the fonts through your laptop before using them, I don’t think this causes the issue. Clearly there is something weird about the font, which some programs can read and others can’t, and non-standard metadata like the ones Alice points out is a good candidate.

**Comment by EwonRael** [comment] 2019-02-03 16:41
Okay but it's not totally unreasonable to think it has something to do with my laptop because I made version 1.2 on my laptop. The only two differences between version 1.1 and 1.2 is the metadata and the laptop. 

Like I said I cannot recreate this issue, so the fact that the working oft files are able to be previewed in Google Drive and the non working otf files cannot seemed like a good metric to use as to weather or not the oft files would have this issue in Microsoft or not.

Clearly that is not the case.

**Comment by EwonRael** [comment] 2019-02-03 19:51
Hey guys check the latest version. 

The TTF files are the same, which means they have issues with the ligatures, but the OTF files should be fixed.

It's important to me that these kind of fixes get out asap so I haven't done an official update, but when I get the chance I will release 1.3.

**Comment by Alice196498** [comment] 2019-02-04 01:01
The new OTF files appear to be fixed from what I can ſee, but it would be moſt prudent to await the reſults from everyone elſe participating in this iſſue.

**Comment by EwonRael** [comment] 2019-02-04 01:02
Okay good. Fingers crossed. I want to move on!

**Comment by thiagovscoelho** [comment] 2019-02-04 12:58
![winword_2019-02-04_10-53-49](https://user-images.githubusercontent.com/47187428/52209506-4a058c00-286b-11e9-9efe-c25bce35013d.png)
The new “Finished” OTFs work perfectly, if you ignore the visual weirdness in the fonts list there. Great! However, the 11 point optical size (and only that one) has no style links. This was so weird that I thought I had kept the v1 version of those, so I rebooted my PC and deleted all of them, but when I reinstalled from the “Finished” folder I still saw this. Did you do anything differently in the 11 point files?
![explorer_2019-02-04_10-27-27](https://user-images.githubusercontent.com/47187428/52209635-a799d880-286b-11e9-90a3-c6cef38410c9.png)
Also, when I went to delete the fonts they looked like the above. Weird, but I can just ignore these visual quirks if it works fine otherwise, which it does, though more so for point sizes above 11.

**Comment by Alice196498** [comment] 2019-02-04 13:11
When uninſtalling founts, it’s beſt to do it the way I ſpoke of earlier while in Safe Mode. The reaſon for this is that Windows has a very peculiar way of dealing with them, and if you uninſtall and reinſtall them, it’s very likely to break ſomething. That’s why I highly recommend checking that folder to make ſure that no copies or other ſtrange things are lingering.

**Comment by thiagovscoelho** [comment] 2019-02-04 14:10
I uninstalled from the Control Panel first, since when I delete from the file explorer directly, Windows sometimes still thinks they’re installed. Windows said it couldn’t delete them because they were in use, so I turned the computer off and on again and did it. Then I checked the Windows\Fonts folder in the file explorer and made sure that the Bodoni* files were no longer there. I don’t know of anything else that could be done. When lunch time comes by, I think I’ll try the files in one of the other W7 PCs in the office, which have never had them installed.

**Comment by Alice196498** [comment] 2019-02-04 14:25
You need to go to \\<name of computer>\c$\Windows\Fonts\ while in Safe Mode, or uſe the Command Prompt therein and delete them from this ſame folder. Other than the Control Panel, Windows likes to hide founts here, and having copies or other lingering verſions cauſes trouble.

**Comment by Alice196498** [comment] 2019-02-04 14:30
Yes, that does ſeem to be the caſe.

**Comment by EwonRael** [comment] 2019-02-04 17:44
oof.

I have remade Bodoni* 11. The metadata issue seems to only have impacted book and bold.
Style links should be okay now.

**Comment by thiagovscoelho** [comment] 2019-02-04 18:52
I tested it and it’s true. Style links and ligatures working, and the fonts are visible, of course. OTFs are now pristine!
![winword_2019-02-04_16-44-59](https://user-images.githubusercontent.com/47187428/52229821-fad84f00-289c-11e9-9795-69c77624d58a.png)

**Comment by thiagovscoelho** [comment] 2019-02-04 18:58
I assume the weird font list entries can’t be reproduced elsewhere, as they weren’t on Jessica’s computer. You should publish these OTFs in indestructibletype.com, IMO.

**Comment by davelab6** [comment] 2019-11-25 22:07
@Alice196498 @thiagovscoelho please could you test the latest versions?

**Comment by Alice196498** [comment] 2019-11-26 00:59
I have teſted it on two computers, and it ſeems that ligatures are ſomewhat broken, and the fatface is not linked with the other ſtyles—at leaſt in Notepad ; they ſeem to work as intended in InDeſign.

**Closed** 2020-05-04 07:24 UTC
